param([ValidateSet('dev','qa','prd')][string]$EnvName='dev')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

$script:S=[ordered]@{
  Env=$EnvName; Compose=''; Project=''; Stack=''; Label=''; ComposeExe=''; ComposePrefix=@()
  BackupDir='docker-backups'; PortainerName='portainer'; PortainerImage='portainer/portainer-ce:latest'
  DataRoot=''; LogsRoot=''; VolumesRoot=''; Profiles=@(); Services=@()
}

function C($m,[ConsoleColor]$c='Gray'){Write-Host $m -ForegroundColor $c}
function Pause-Menu(){''|Write-Host; Read-Host 'Presione Enter para continuar'|Out-Null}
function Exit-Script(){Clear-Host; C '============================================================' Cyan; C '   Gracias por usar Docker Tools Windows' Green; C '============================================================' Cyan; exit 0}
function Compose-File(){switch($script:S.Env){'dev'{'docker-compose-dev.yml'}'qa'{'docker-compose-qa.yml'}'prd'{'docker-compose.yml'}default{'docker-compose-dev.yml'}}}
function Env-Files(){@('.env',".env.$($script:S.Env)")}
function Parse-Env(){ $h=@{}; foreach($f in Env-Files){ if(Test-Path $f){ foreach($l in Get-Content $f){ if($l -match '^\s*#|^\s*$'){continue}; if($l -match '^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$'){ $v=$Matches[2].Trim(); if((($v.StartsWith('"')) -and $v.EndsWith('"')) -or (($v.StartsWith("'")) -and $v.EndsWith("'"))){$v=$v.Substring(1,$v.Length-2)}; $h[$Matches[1]]=$v } } } }; $h }
function Env($k,$d=''){ $h=Parse-Env; if($h.ContainsKey($k) -and -not [string]::IsNullOrWhiteSpace($h[$k])){$h[$k]}else{$d} }
function Abs([string]$p){ if([string]::IsNullOrWhiteSpace($p)){return ''}; if([IO.Path]::IsPathRooted($p)){return $p}; [IO.Path]::GetFullPath((Join-Path (Get-Location) $p)) }
function Refresh-State(){ $script:S.Compose=Compose-File; $script:S.Project=Env 'PROJECT_NAME'; $script:S.Stack=if([string]::IsNullOrWhiteSpace($script:S.Project)){'NoExisteStackName'}else{$script:S.Project}; $script:S.Label="stack=$($script:S.Stack)"; $script:S.DataRoot=Abs (Env 'DATA_ROOT' "./APP/data/$($script:S.Env)"); $script:S.LogsRoot=Abs (Env 'LOGS_ROOT' "./APP/logs/$($script:S.Env)"); $script:S.VolumesRoot=Abs (Env 'VOLUMES_ROOT' './APP/volumes') }
function Current-IP(){ try{ $ip=Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop|?{ $_.IPAddress -notmatch '^(127|169\.254)\.' -and $_.InterfaceAlias -notmatch 'Loopback|Default Switch|isatap|Teredo'}|select -Expand IPAddress -First 1; if($ip){return $ip}}catch{}; try{ $m=(ipconfig|sls 'IPv4.*?:\s*([0-9\.]+)'|select -First 1); if($m){return $m.Matches[0].Groups[1].Value}}catch{}; '' }
function Git-Branch(){ try{ $r=& git rev-parse --is-inside-work-tree 2>$null; if($LASTEXITCODE -eq 0 -and $r -contains 'true'){ return (& git rev-parse --abbrev-ref HEAD 2>$null|select -First 1)}}catch{}; '' }
function Banner([string]$t){ Clear-Host; $ip=Current-IP; $branch=Git-Branch; if(-not $ip){$ip='No detectada'}; if(-not $branch){$branch='No es repositorio Git'}; C '+===========================================================+' Cyan; C ("|         DOCKER TOOLS WINDOWS - {0,-20}|" -f $t) Cyan; C '+===========================================================+' Cyan; ''; C '[INFO] ENTORNO:' Blue; "   Archivo:  $($script:S.Compose)"; "   Stack:    $($script:S.Stack)"; "   Entorno:  $($script:S.Env)"; "   IP Actual: $ip"; "   Rama Git: $branch"; '   Sistema:  Windows nativo / PowerShell'; '' }
function Ask([string]$m,[ValidateSet('si','no')][string]$d='no'){ ''; C '[!] CONFIRMACION REQUERIDA' Yellow; C '------------------------------------------------------------' Yellow; $m; ''; $p=if($d -eq 'si'){'Continuar? [S/n]'}else{'Continuar? [s/N]'}; $r=Read-Host $p; if([string]::IsNullOrWhiteSpace($r)){$r=if($d -eq 'si'){'S'}else{'N'}}; $r -match '^[Ss]$' }
function Need($cmd){ $null -ne (Get-Command $cmd -ErrorAction SilentlyContinue) }
function Init-Compose(){ if(Need 'docker'){ & docker compose version *> $null; if($LASTEXITCODE -eq 0){$script:S.ComposeExe='docker';$script:S.ComposePrefix=@('compose'); return} }; if(Need 'docker-compose'){ $script:S.ComposeExe='docker-compose'; $script:S.ComposePrefix=@(); return }; throw 'Docker Compose no esta disponible.' }
function Native($exe,[string[]]$args=@(),[switch]$Capture){ if($Capture){ $o=& $exe @args 2>&1; [pscustomobject]@{Output=@($o); ExitCode=$LASTEXITCODE} } else { & $exe @args; $LASTEXITCODE } }
function Docker([string[]]$args,[switch]$Capture){ Native 'docker' $args -Capture:$Capture }
function Compose([string[]]$args,[string[]]$profiles=@(),[string[]]$services=@(),[switch]$Capture){ $a=@(); $a+=$script:S.ComposePrefix; $a+=@('-f',$script:S.Compose); foreach($f in Env-Files){$a+=@('--env-file',$f)}; foreach($p in $profiles){$a+=@('--profile',$p)}; $a+=$args; $a+=$services; Native $script:S.ComposeExe $a -Capture:$Capture }
function Check-EnvFiles(){ $miss=@(); foreach($f in Env-Files){ if(-not(Test-Path $f)){$miss+=$f}}; if($miss.Count){ C '[ERR] Faltan archivos de entorno requeridos:' Red; $miss|%{"      - $_"}; ''; return $false }; $txt=Get-Content $script:S.Compose -Raw; $vars=[regex]::Matches($txt,'\$\{([A-Z0-9_]+)(?::-[^}]*)?\}')|%{$_.Groups[1].Value}|sort -Unique; $opt=@('ITOP_PACKAGE_URL'); $bad=@(); foreach($v in $vars){ if($opt -contains $v){continue}; if([string]::IsNullOrWhiteSpace((Env $v))){$bad+=$v} }; if($bad.Count){ C "[ERR] Variables requeridas sin valor para $($script:S.Compose):" Red; $bad|%{"      - $_"}; ''; return $false }; $true }
function Test-Dependencies(){ Banner 'DEPENDENCIAS'; $bad=$false; if(-not(Need 'docker')){C '[ERR] Docker CLI: No encontrado' Red; $bad=$true}else{C '[OK]  Docker CLI: Encontrado' Green; $i=Docker @('info') -Capture; if($i.ExitCode -ne 0){C '[ERR] Docker daemon: No esta en ejecucion' Red; $bad=$true}else{C '[OK]  Docker daemon: En ejecucion' Green}}; try{Init-Compose; C '[OK]  Docker Compose: Encontrado' Green}catch{C '[ERR] Docker Compose: No encontrado' Red; $bad=$true}; if($bad){throw 'Faltan dependencias para Docker Tools.'}; ''; C '[OK]  Verificacion de dependencias completada' Green; Start-Sleep 1 }
function Project-Run([scriptblock]$a,[string]$err,[string]$ok){ try{ & $a; if($LASTEXITCODE -ne 0){C "[ERR] $err (codigo: $LASTEXITCODE)" Red; return $false}; C "[OK]  $ok" Green; $true }catch{C "[ERR] $err" Red; $_; $false} }
function Compose-Services(){ $r=Compose @('config','--services') @('tools') -Capture; if($r.ExitCode -ne 0){@()}else{@($r.Output|?{$_})} }
function Service-Block([string]$svc){ $lines=Get-Content $script:S.Compose; $inServices=$false; $inTarget=$false; $out=New-Object Collections.Generic.List[string]; $pat='^\s{2}'+[regex]::Escape($svc)+':\s*$'; foreach($line in $lines){ if(-not $inServices){ if($line -match '^services:\s*$'){$inServices=$true}; continue }; if($inTarget){ if($line -match '^\s{2}[A-Za-z0-9_-]+:\s*$' -or $line -match '^[^\s]'){break}; [void]$out.Add($line); continue }; if($line -match $pat){$inTarget=$true; [void]$out.Add($line); continue}; if($line -match '^[^\s]' -and $line -notmatch '^services:\s*$'){break} }; @($out) }
function Service-Group([string]$svc){ foreach($line in Service-Block $svc){ if($line -match '^\s+service\.group:\s*(.+?)\s*$'){ return $Matches[1].Trim(" '""") } }; '' }
function Group-Services([string]$g='all'){ $l=New-Object Collections.Generic.List[string]; foreach($s in Compose-Services){ if($g -eq 'all' -or (Service-Group $s) -eq $g){ [void]$l.Add($s) } }; @($l) }
function Choose-Groups(){ $script:S.Profiles=@(); $script:S.Services=@(); $core=Group-Services 'core'; $dep=Group-Services 'dependency'; $tools=Group-Services 'tools'; $sel=New-Object Collections.Generic.List[string]; $core|%{[void]$sel.Add($_)}; ''; C '[*] ALCANCE DEL LEVANTE' Cyan; C '----------------------------------------' Cyan; "El grupo base para el entorno $($script:S.Env) sera siempre core."; ''; if($dep.Count){ 'Dependencias disponibles:'; $dep|%{"   * $_"}; if(Ask 'Desea anexar dependency?' 'no'){ $dep|%{[void]$sel.Add($_)} } }; if($tools.Count){ ''; 'Herramientas disponibles:'; $tools|%{"   * $_"}; if(Ask 'Desea anexar tools?' 'no'){ $script:S.Profiles=@('tools'); $tools|%{[void]$sel.Add($_)} } }; $script:S.Services=@($sel) }
function Stack-Containers([switch]$All){ $args=if($All){@('ps','-a')}else{@('ps')}; $args+=@('--filter',"label=$($script:S.Label)",'--format','{{.ID}}|{{.Names}}|{{.Image}}|{{.Status}}|{{.Ports}}'); $r=Docker $args -Capture; if($r.ExitCode -ne 0){return @()}; $o=New-Object Collections.Generic.List[object]; foreach($line in $r.Output){ if(-not $line){continue}; $p=$line -split '\|',5; [void]$o.Add([pscustomobject]@{Id=$p[0];Name=$p[1];Image=$p[2];Status=$p[3];Ports=if($p.Count -gt 4){$p[4]}else{''}}) }; @($o) }
function Show-Containers([switch]$All,[switch]$Detailed){ $items=Stack-Containers -All:$All; if(-not $items.Count){ C "[WARN] No se encontraron contenedores con etiqueta: $($script:S.Label)" Yellow; return @() }; ''; if($Detailed){ $items|% -Begin{$i=1} -Process{ "{0,2}) {1,-25} {2,-28} {3,-20} {4}" -f $i,$_.Name,$_.Image,$_.Status,$_.Ports; $i++ } } else { $items|% -Begin{$i=1} -Process{ "{0,2}) {1,-30} {2}" -f $i,$_.Name,$_.Status; $i++ } }; $items }
function Pick-Container([string]$prompt='Seleccione el numero del contenedor',[switch]$All){ ''; C '[*] CONTENEDORES DISPONIBLES:' Cyan; $items=Show-Containers -All:$All -Detailed; if(-not $items.Count){return $null}; ''; "{0,2}) Volver al menu anterior" -f ($items.Count+1); $ch=Read-Host $prompt; if($ch -eq '0' -or $ch -eq ($items.Count+1).ToString()){return $null}; $i=0; if(-not [int]::TryParse($ch,[ref]$i) -or $i -lt 1 -or $i -gt $items.Count){ C '[ERR] Opcion invalida' Red; Start-Sleep 2; return $null }; $items[$i-1] }
function Container-Shell([string]$id){ foreach($c in @('bash','sh')){ $r=Docker @('exec',$id,$c,'-c','echo ok') -Capture; if($r.ExitCode -eq 0){return $c} }; 'sh' }
function Named-Volumes(){ $r=Docker @('volume','ls','--format','{{.Name}}') -Capture; if($r.ExitCode -ne 0){@()}else{@($r.Output|?{$_ -like "$($script:S.Project)_*"})} }
function Backup-Path(){ $p=Join-Path (Get-Location) $script:S.BackupDir; if(-not(Test-Path $p)){New-Item -ItemType Directory -Path $p|Out-Null}; (Resolve-Path $p).Path }
function Backup-VolumeName([string]$f){ ([IO.Path]::GetFileNameWithoutExtension([IO.Path]::GetFileNameWithoutExtension($f))) -replace '_\d{8}_\d{6}$','' }
function Clear-Dir([string]$dir,[string]$label){ if(-not(Test-Path $dir -PathType Container)){ C "[WARN] No existe el directorio $dir" Yellow; return }; $items=@(Get-ChildItem $dir -Force|?{$_.Name -ne '.gitkeep'}); if(-not $items.Count){ C "[WARN] $label ya esta vacio" Yellow; return }; foreach($it in $items){ try{ Remove-Item $it.FullName -Recurse -Force; C "[OK]  Eliminado: $($it.FullName)" Green }catch{ C "[ERR] Error al eliminar $($it.FullName)" Red } } }
function Clear-Artifacts(){ $t=@('node_modules','__pycache__','.pytest_cache','.mypy_cache','.ruff_cache','.venv','venv','dist','build','coverage'); if(-not(Test-Path $script:S.VolumesRoot -PathType Container)){ C "[WARN] No existe el directorio $($script:S.VolumesRoot)" Yellow; return }; $rm=$false; Get-ChildItem $script:S.VolumesRoot -Force -Recurse -ErrorAction SilentlyContinue|%{ if($_.FullName -match '\\\.git(\\|$)'){return}; if($t -contains $_.Name -or (-not $_.PSIsContainer -and $_.Extension -in '.pyc','.pyo')){ try{ Remove-Item $_.FullName -Recurse -Force; C "[OK]  Eliminado: $($_.FullName)" Green; $rm=$true }catch{ C "[ERR] Error al eliminar $($_.FullName)" Red } } }; if(-not $rm){ C '[WARN] No se encontraron artefactos de runtime' Yellow } }
function Set-EnvValue([string]$file,[string]$key,[string]$value){ $c=if(Test-Path $file){Get-Content $file}else{@()}; $u=$false; $pat='^\s*'+[regex]::Escape($key)+'='; $n=foreach($l in $c){ if($l -match $pat){$u=$true;"$key=$value"}else{$l} }; if(-not $u){$n+="$key=$value"}; if(Test-Path $file){Copy-Item $file "$file.bak" -Force}; Set-Content $file $n }
function DockerDesktop-Path(){ foreach($p in @((Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'),(Join-Path $env:LocalAppData 'Programs\Docker\Docker\Docker Desktop.exe'))){ if(Test-Path $p){return $p} }; '' }
function Up{ Banner 'INICIAR CONTENEDORES'; if(-not(Check-EnvFiles)){Pause-Menu;return}; Choose-Groups; Project-Run { Compose @('up','-d','--build') $script:S.Profiles $script:S.Services | Out-Null } 'Error al iniciar contenedores' 'Contenedores iniciados exitosamente'|Out-Null; Pause-Menu }
function Down{ Banner 'DETENER CONTENEDORES'; if(-not(Check-EnvFiles)){Pause-Menu;return}; if(Ask 'Detener y eliminar todos los contenedores del stack?' 'no'){ Project-Run { Compose @('down') | Out-Null } 'Error al detener contenedores' 'Contenedores detenidos exitosamente'|Out-Null }; Pause-Menu }
function Restart-Stack{ Banner 'REINICIAR CONTENEDORES'; if(-not(Check-EnvFiles)){Pause-Menu;return}; if(Ask 'Reiniciar los contenedores seleccionados del stack?' 'no'){ Choose-Groups; Project-Run { Compose @('down') | Out-Null } 'Error al detener contenedores' 'Stack detenido'|Out-Null; Project-Run { Compose @('up','-d','--build') $script:S.Profiles $script:S.Services | Out-Null } 'Error al iniciar contenedores' 'Contenedores reiniciados exitosamente'|Out-Null }; Pause-Menu }
function Restart-One{ Banner 'REINICIAR CONTENEDOR UNICO'; $c=Pick-Container 'Seleccione contenedor a reiniciar' -All; if(-not $c){return}; if(Ask "Reiniciar contenedor $($c.Name)?" 'no'){ Project-Run { Docker @('restart',$c.Id)|Out-Null } 'Error al reiniciar contenedor' 'Contenedor reiniciado exitosamente'|Out-Null }; Pause-Menu }
function Build-Images{ Banner 'CONSTRUIR IMAGENES'; if(-not(Check-EnvFiles)){Pause-Menu;return}; Choose-Groups; Project-Run { Compose @('build') $script:S.Profiles $script:S.Services | Out-Null } 'Error al construir imagenes' 'Imagenes construidas exitosamente'|Out-Null; Pause-Menu }
function Logs{ Banner 'VER LOGS'; if(-not(Check-EnvFiles)){Pause-Menu;return}; Compose @('logs','-f'); Pause-Menu }
function Logs-One{ Banner 'LOGS DE CONTENEDOR'; $c=Pick-Container 'Seleccione contenedor para ver logs' -All; if(-not $c){return}; Docker @('logs','-f',$c.Id); Pause-Menu }
function Ps-Stack{ Banner 'ESTADO DE CONTENEDORES'; if(-not(Check-EnvFiles)){Pause-Menu;return}; Compose @('ps'); Pause-Menu }
function List-Stack{ Banner 'LISTAR CONTENEDORES'; Show-Containers -All -Detailed|Out-Null; Pause-Menu }
function Exec-Stack{ Banner 'TERMINAL EN CONTENEDOR'; $c=Pick-Container 'Seleccione contenedor para acceder' -All; if(-not $c){return}; ''; '1) Usuario normal del contenedor'; '2) root'; $mode=Read-Host 'Seleccione modo de acceso'; $sh=Container-Shell $c.Id; $a=@('exec','-it'); if($mode -eq '2'){$a+=@('--user','root')}; $a+=@($c.Id,$sh); Docker $a; Pause-Menu }
function Monitor-Resources{ Banner 'MONITOREO DE RECURSOS'; C 'Presione Ctrl+C para salir del stream y volver al menu.' Yellow; ''; Docker @('stats','--filter',"label=$($script:S.Label)",'--format','table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}'); Pause-Menu }
function Clean-Stack{ Banner 'LIMPIEZA DE RECURSOS'; if(-not(Check-EnvFiles)){Pause-Menu;return}; if(Ask 'Limpiar contenedores, redes y volumenes del stack?' 'no'){ Project-Run { Compose @('down','--volumes','--remove-orphans')|Out-Null } 'Error durante la limpieza' 'Limpieza completada'|Out-Null }; Pause-Menu }
function Clean-Images{ Banner 'LIMPIEZA DE IMAGENES'; $i=Docker @('images','-q') -Capture; $d=Docker @('images','-f','dangling=true','-q') -Capture; "Total de imagenes: $(@($i.Output|?{$_}).Count)"; "Imagenes huerfanas: $(@($d.Output|?{$_}).Count)"; ''; if(@($d.Output|?{$_}).Count -gt 0 -and (Ask 'Eliminar imagenes huerfanas?' 'si')){ Docker @('image','prune','-f')|Out-Null }; if(Ask 'Eliminar todas las imagenes no utilizadas?' 'no'){ Docker @('image','prune','-a','-f')|Out-Null; C '[OK]  Imagenes no utilizadas eliminadas' Green }; Pause-Menu }
function Clean-Volumes{ Banner 'LIMPIAR VOLUMENES'; if(Ask 'Eliminar todos los volumenes no utilizados?' 'no'){ Docker @('volume','prune','-f')|Out-Null; C '[OK]  Volumenes no utilizados eliminados' Green }; Pause-Menu }
function Clean-All{ Banner 'LIMPIEZA COMPLETA'; if(-not(Check-EnvFiles)){Pause-Menu;return}; C '[!] ADVERTENCIA: limpieza profunda del sistema' Red; '   * Contenedores, redes y volumenes del stack'; '   * Volumenes huerfanos del stack'; '   * Imagenes no utilizadas'; '   * Cache de builds'; ''; if(-not(Ask 'Iniciar limpieza completa?' 'no')){return}; Compose @('down','--volumes','--remove-orphans')|Out-Null; Docker @('volume','prune','-f')|Out-Null; Docker @('image','prune','-a','-f')|Out-Null; Docker @('builder','prune','-a','-f')|Out-Null; C '[OK]  Limpieza completa finalizada' Green; Pause-Menu }
function Drop-Persistence{ Banner 'ELIMINAR PERSISTENCIAS'; C '[!] ADVERTENCIA: esta accion eliminara:' Red; '   * Volumenes Docker nombrados del proyecto'; "   * Artefactos de runtime en $($script:S.VolumesRoot)"; "   * Datos de $($script:S.DataRoot)"; "   * Logs de $($script:S.LogsRoot)"; ''; if(-not(Ask 'Eliminar todas las persistencias?' 'no')){Pause-Menu;return}; if(Ask 'Eliminar volumenes Docker nombrados del proyecto?' 'no'){ Named-Volumes|%{ Docker @('volume','rm',$_)|Out-Null; C "[OK]  Eliminado: $_" Green } }; if(Ask "Eliminar artefactos de runtime en $($script:S.VolumesRoot)?" 'no'){ Clear-Artifacts }; if(Ask "Eliminar carpetas de $($script:S.DataRoot)?" 'no'){ Clear-Dir $script:S.DataRoot 'datos persistentes' }; if(Ask "Eliminar contenido de $($script:S.LogsRoot)?" 'no'){ Clear-Dir $script:S.LogsRoot 'logs persistentes' }; Pause-Menu }
function Change-Env{ Banner 'CAMBIAR ENTORNO'; "Entorno actual: $($script:S.Env)"; ''; '1) dev'; '2) qa'; '3) prd'; ''; switch(Read-Host 'Seleccione nuevo entorno'){ '1'{$script:S.Env='dev'} '2'{$script:S.Env='qa'} '3'{$script:S.Env='prd'} default{C '[ERR] Opcion invalida' Red; Start-Sleep 2; return} }; Refresh-State; C "[OK]  Entorno cambiado a: $($script:S.Env)" Green; Pause-Menu }
function Update-IP{ Banner 'ACTUALIZAR IP EXPO / ANDROID'; $ip=Current-IP; if([string]::IsNullOrWhiteSpace($ip)){ C '[WARN] No se pudo detectar IP automaticamente' Yellow; $ip=Read-Host 'Ingrese IP manualmente' }; "IP actual detectada: $ip"; 'Se usara para REACT_NATIVE_PACKAGER_HOSTNAME en .env'; if(Ask "Actualizar REACT_NATIVE_PACKAGER_HOSTNAME en .env a $ip?" 'si'){ Set-EnvValue '.env' 'REACT_NATIVE_PACKAGER_HOSTNAME' $ip; C '[OK]  IP actualizada exitosamente' Green }; Pause-Menu }
function Check-IP{ Banner 'VERIFICAR IP EXPO / ANDROID'; $ip=Current-IP; $envIp=Env 'REACT_NATIVE_PACKAGER_HOSTNAME'; if(-not $ip){$ip='No detectada'}; if(-not $envIp){$envIp='No configurada'}; "IP actual del equipo: $ip"; "REACT_NATIVE_PACKAGER_HOSTNAME en .env: $envIp"; if($ip -ne 'No detectada' -and $envIp -ne 'No configurada'){ if($ip -eq $envIp){C '[OK]  Las IPs coinciden' Green}else{C '[WARN] Las IPs no coinciden' Yellow} }; Pause-Menu }
function Container-Env{ Banner 'VARIABLES DE ENTORNO'; $c=Pick-Container 'Seleccione contenedor' -All; if(-not $c){return}; $r=Docker @('exec',$c.Id,'env') -Capture; if($r.ExitCode -ne 0){ C '[ERR] No se pudieron listar las variables del contenedor' Red } else { $i=1; foreach($l in ($r.Output|sort)){ '{0,3} {1}' -f $i,$l; $i++ } }; Pause-Menu }
function Validate-Compose{ Banner 'VALIDAR DOCKER COMPOSE'; if(-not(Check-EnvFiles)){Pause-Menu;return}; $r=Compose @('config') -Capture; if($r.ExitCode -eq 0){ C '[OK]  VALIDACION EXITOSA' Green; ''; 'SERVICIOS CONFIGURADOS:'; (Compose @('config','--services') -Capture).Output|?{$_}|%{"   * $_"} } else { C '[ERR] ERROR DE VALIDACION' Red; $r.Output|%{$_} }; Pause-Menu }
function Validate-Rules{ Banner 'VALIDAR REGLAS DEL COMPOSE'; if(-not(Check-EnvFiles)){Pause-Menu;return}; $exp=Compose @('config') @('tools') -Capture; if($exp.ExitCode -ne 0){ C '[ERR] No se pudo expandir la configuracion de Compose' Red; Pause-Menu; return }; $errors=0; $warnings=0; foreach($s in Compose-Services){ $src=(Service-Block $s) -join "`n"; $blk=$exp.Output|sls "^\s{2}$([regex]::Escape($s)):\s*$" -Context 0,30|select -First 1; $txt=if($blk){($blk.Context.PreContext+$blk.Line+$blk.Context.PostContext)-join "`n"}else{''}; $expName="$($script:S.Project)-$s"; C "Servicio: $s" Blue; if($txt -match "container_name:\s*$([regex]::Escape($expName))"){C "   [OK]  container_name correcto ($expName)" Green}else{C "   [ERR] container_name invalido. Se espera $expName" Red; $errors++}; if($txt -match "stack:\s*$([regex]::Escape($script:S.Project))"){C '   [OK]  label stack correcto' Green}else{C "   [ERR] falta label stack=$($script:S.Project)" Red; $errors++}; if($txt -match "env:\s*$([regex]::Escape($script:S.Env))"){C '   [OK]  label env correcto' Green}else{C "   [ERR] falta label env=$($script:S.Env)" Red; $errors++}; $g=Service-Group $s; if($g -in @('core','dependency','tools')){C "   [OK]  service.group valido ($g)" Green}else{C '   [ERR] service.group invalido o ausente' Red; $errors++}; if($txt -match 'service\.lifecycle:'){C '   [OK]  service.lifecycle presente' Green}else{C '   [ERR] falta service.lifecycle' Red; $errors++}; if($src -match 'Data/dokerFile|persistence/|APP/data-prd|APP/data-qa|APP/logs-prd|APP/logs-qa|APP/data/settings'){C '   [ERR] el servicio usa rutas legacy' Red; $errors++}; if($src -match '^\s+- \./'){C '   [WARN] mounts con rutas relativas directas; revisar si deben usar variables' Yellow; $warnings++}; '' }; C '============================================================' Cyan; if($errors -eq 0){C '[OK]  VALIDACION DE REGLAS SUPERADA' Green}else{C '[ERR] VALIDACION DE REGLAS CON ERRORES' Red}; "Errores: $errors"; "Advertencias: $warnings"; C '============================================================' Cyan; Pause-Menu }
function Backup-Volumes{ Banner 'BACKUP DE VOLUMENES'; $vols=Named-Volumes; if(-not $vols.Count){ C '[WARN] No hay volumenes nombrados del proyecto' Yellow; Pause-Menu; return }; for($i=0;$i -lt $vols.Count;$i++){ "{0,2}) {1}" -f ($i+1),$vols[$i] }; ' T) Todos los volumenes'; ' V) Volver al menu anterior'; $ch=Read-Host 'Seleccione volumen a respaldar'; if($ch -match '^[Vv]$'){return}; $sel=@(); if($ch -match '^[Tt]$'){$sel=$vols}else{ $i=0; if(-not [int]::TryParse($ch,[ref]$i) -or $i -lt 1 -or $i -gt $vols.Count){ C '[ERR] Opcion invalida' Red; Pause-Menu; return }; $sel=@($vols[$i-1]) }; $ts=Get-Date -Format 'yyyyMMdd_HHmmss'; $bp=Backup-Path; foreach($v in $sel){ $f="${v}_${ts}.tar.gz"; C "Respaldando volumen: $v" Blue; Docker @('run','--rm','-v',"${v}:/source",'-v',"${bp}:/backup",'alpine','sh','-c',"tar czf /backup/$f -C /source .")|Out-Null; if($LASTEXITCODE -eq 0){ C "[OK]  Backup creado: $f" Green } else { C "[ERR] Error al respaldar $v" Red } }; Pause-Menu }
function Restore-Volume{ Banner 'RESTAURAR VOLUMEN'; $bp=Backup-Path; $bk=@(Get-ChildItem $bp -Filter '*.tar.gz' -File -ErrorAction SilentlyContinue|sort Name); if(-not $bk.Count){ C '[WARN] No hay backups disponibles' Yellow; Pause-Menu; return }; for($i=0;$i -lt $bk.Count;$i++){ "{0,2}) {1} [{2}]" -f ($i+1),$bk[$i].Name,$bk[$i].Length }; $ch=Read-Host 'Seleccione backup a restaurar'; $i=0; if(-not [int]::TryParse($ch,[ref]$i) -or $i -lt 1 -or $i -gt $bk.Count){ C '[ERR] Opcion invalida' Red; Pause-Menu; return }; $b=$bk[$i-1]; $v=Backup-VolumeName $b.Name; ''; "Se restaurara el volumen: $v"; if(-not(Ask 'Continuar con la restauracion?' 'no')){return}; $ex=Docker @('volume','ls','--format','{{.Name}}') -Capture; if($ex.Output -contains $v){ if(Ask 'Eliminar volumen existente antes de restaurar?' 'no'){ Docker @('volume','rm',$v)|Out-Null } else { return } }; Docker @('volume','create',$v)|Out-Null; Docker @('run','--rm','-v',"${v}:/target",'-v',"${bp}:/backup",'alpine','sh','-c',"tar xzf /backup/$($b.Name) -C /target")|Out-Null; if($LASTEXITCODE -eq 0){ C '[OK]  Volumen restaurado exitosamente' Green } else { C '[ERR] Error al restaurar el volumen' Red }; Pause-Menu }
function Menu-Templates{ Banner 'GESTION DE TEMPLATES .ENV'; '1) Generar .env.template'; '2) Generar archivos .env desde template'; '3) Verificar archivos .env'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1' {C '[WARN] Funcion en desarrollo' Yellow; Pause-Menu} '2' {C '[WARN] Funcion en desarrollo' Yellow; Pause-Menu} '3' {C '[WARN] Funcion en desarrollo' Yellow; Pause-Menu} 'V' {return} 'v' {return} 'S' {Exit-Script} 's' {Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } }
function Menu-Expo{ Banner 'HERRAMIENTAS EXPO'; '1) Iniciar Expo Development Server'; '2) EAS Build'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1' {C '[WARN] Funcion en desarrollo' Yellow; Pause-Menu} '2' {C '[WARN] Funcion en desarrollo' Yellow; Pause-Menu} 'V' {return} 'v' {return} 'S' {Exit-Script} 's' {Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } }
function Menu-DockerServices{ while($true){ Banner 'ESTADO Y SERVICIOS DOCKER'; '1) Estado Docker Engine'; '2) Estado Docker Desktop'; '3) Reiniciar Docker Engine'; '4) Reiniciar Docker Desktop'; '5) Reiniciar Ambos'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1' {Docker @('info'); Pause-Menu} '2' { $p=Get-Process -ErrorAction SilentlyContinue|?{$_.ProcessName -like '*docker*'}|select -First 1; if($p){C '[OK]  Docker Desktop esta en ejecucion' Green}else{C '[WARN] Docker Desktop no parece estar en ejecucion' Yellow}; Pause-Menu } '3' {C '[INFO] En Windows el engine se administra desde Docker Desktop.' Yellow; Pause-Menu} '4' { if(Ask 'Reiniciar Docker Desktop?' 'no'){ Get-Process -ErrorAction SilentlyContinue|?{$_.ProcessName -like '*docker*'}|%{ try{Stop-Process -Id $_.Id -Force -ErrorAction Stop}catch{} }; Start-Sleep 3; $p=DockerDesktop-Path; if($p){ Start-Process $p; C '[OK]  Docker Desktop iniciado' Green } else { C '[WARN] No se encontro el ejecutable de Docker Desktop. Inicielo manualmente.' Yellow }; Pause-Menu } } '5' {C '[INFO] En Windows reiniciar Docker Desktop reinicia ambos componentes.' Yellow; Pause-Menu} 'V' {return} 'v' {return} 'S' {Exit-Script} 's' {Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Menu-Portainer{ while($true){ Banner 'PORTAINER'; '1) Iniciar Portainer'; '2) Detener Portainer'; '3) Reiniciar Portainer'; '4) Abrir en navegador'; '5) Ver logs'; '6) Recrear Portainer'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1' { $n=Docker @('ps','-a','--format','{{.Names}}') -Capture; if($n.Output -notcontains $script:S.PortainerName){ Docker @('run','-d','--name',$script:S.PortainerName,'--restart','unless-stopped','-p','9000:9000','-v','//var/run/docker.sock:/var/run/docker.sock','-v','portainer_data:/data',$script:S.PortainerImage)|Out-Null } else { Docker @('start',$script:S.PortainerName)|Out-Null }; C '[OK]  Portainer disponible en http://localhost:9000' Green; Pause-Menu } '2' {Docker @('stop',$script:S.PortainerName)|Out-Null; Pause-Menu} '3' {Docker @('restart',$script:S.PortainerName)|Out-Null; Pause-Menu} '4' {Start-Process 'http://localhost:9000'; Pause-Menu} '5' {Docker @('logs','--tail','50',$script:S.PortainerName); Pause-Menu} '6' { if(Ask 'Recrear contenedor Portainer?' 'no'){ Docker @('stop',$script:S.PortainerName)|Out-Null; Docker @('rm',$script:S.PortainerName)|Out-Null; Docker @('volume','create','portainer_data')|Out-Null; Docker @('run','-d','--name',$script:S.PortainerName,'--restart','unless-stopped','-p','9000:9000','-v','//var/run/docker.sock:/var/run/docker.sock','-v','portainer_data:/data',$script:S.PortainerImage)|Out-Null; C '[OK]  Portainer recreado' Green; Pause-Menu } } 'V' {return} 'v' {return} 'S' {Exit-Script} 's' {Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Menu-Containers{ while($true){ Banner 'MANEJADOR DE CONTENEDORES'; '1) Iniciar contenedores y construir imagenes'; '2) Detener y eliminar contenedores'; '3) Reiniciar contenedores'; '4) Reiniciar contenedor unico'; '5) Construir imagenes'; '6) Validar Docker Compose'; '7) Validar reglas del proyecto'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1'{Up} '2'{Down} '3'{Restart-Stack} '4'{Restart-One} '5'{Build-Images} '6'{Validate-Compose} '7'{Validate-Rules} 'V'{return} 'v'{return} 'S'{Exit-Script} 's'{Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Menu-Monitor{ while($true){ Banner 'MONITOREO Y DIAGNOSTICO'; '1) Ver logs'; '2) Ver logs de un contenedor'; '3) Estado de los contenedores'; '4) Listar contenedores del stack'; '5) Abrir terminal en contenedor'; '6) Monitoreo de recursos'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1'{Logs} '2'{Logs-One} '3'{Ps-Stack} '4'{List-Stack} '5'{Exec-Stack} '6'{Monitor-Resources} 'V'{return} 'v'{return} 'S'{Exit-Script} 's'{Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Menu-Cleanup{ while($true){ Banner 'LIMPIEZA Y MANTENIMIENTO'; '1) Limpiar contenedores, redes y volumenes'; '2) Limpiar imagenes no utilizadas'; '3) Limpiar volumenes no utilizados'; '4) Limpiar todo'; '5) Eliminar persistencias'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1'{Clean-Stack} '2'{Clean-Images} '3'{Clean-Volumes} '4'{Clean-All} '5'{Drop-Persistence} 'V'{return} 'v'{return} 'S'{Exit-Script} 's'{Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Menu-Config{ while($true){ Banner 'CONFIGURACION DEL SISTEMA'; '1) Cambiar entorno (dev, qa, prd)'; '2) Actualizar IP para Expo / Android'; '3) Verificar IP de Expo / Android'; '4) Listar variables de entorno'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1'{Change-Env} '2'{Update-IP} '3'{Check-IP} '4'{Container-Env} 'V'{return} 'v'{return} 'S'{Exit-Script} 's'{Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Menu-Backup{ while($true){ Banner 'BACKUP Y RESTORE'; '1) Backup de volumenes'; '2) Restaurar volumen'; ''; 'V) Volver'; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1'{Backup-Volumes} '2'{Restore-Volume} 'V'{return} 'v'{return} 'S'{Exit-Script} 's'{Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }
function Main-Menu{ while($true){ Banner 'MENU PRINCIPAL'; '1) MANEJADOR DE CONTENEDORES'; '2) MONITOREO Y DIAGNOSTICO'; '3) LIMPIEZA Y MANTENIMIENTO'; '4) CONFIGURACION DEL SISTEMA'; '5) HERRAMIENTAS EXPO'; '6) GESTION DE TEMPLATES .ENV'; '7) ESTADO Y SERVICIOS DOCKER'; '8) PORTAINER'; '9) BACKUP Y RESTORE'; ''; 'S) Salir'; ''; switch(Read-Host 'Seleccione una opcion'){ '1'{Menu-Containers} '2'{Menu-Monitor} '3'{Menu-Cleanup} '4'{Menu-Config} '5'{Menu-Expo} '6'{Menu-Templates} '7'{Menu-DockerServices} '8'{Menu-Portainer} '9'{Menu-Backup} 'S'{Exit-Script} 's'{Exit-Script} default {C '[ERR] Opcion invalida' Red; Start-Sleep 2} } } }

Refresh-State
Test-Dependencies
Main-Menu
