// src/components/ui/icon/categories/actionIcons.js
import {
  FaPenToSquare,
  FaTrash,
  FaDownload,
  FaPlus,
  FaUserPlus,
  FaPrint,
  FaCheck,
  FaThumbtack,
  FaFloppyDisk,
  FaCamera,
  FaKey,
  FaEraser,
  FaPowerOff,
  FaPhone,
  FaEnvelope,
  FaToggleOn,
  FaUserCheck,
  FaCalendarPlus,
  FaPaperPlane,
  FaPaperclip,
  FaRotate,
  FaRotateLeft,
  FaComment,
  FaArrowsRotate,
  FaXmark,
} from "react-icons/fa6";

export const actionIcons = {
  edit: FaPenToSquare,
  pen: FaPenToSquare,
  FaEdit: FaPenToSquare,
  delete: FaTrash,
  download: FaDownload,
  plus: FaPlus,
  userPlus: FaUserPlus,
  print: FaPrint,
  check: FaCheck,
  thumbtack: FaThumbtack,
  save: FaFloppyDisk,
  camera: FaCamera,
  key: FaKey,
  eraser: FaEraser,
  powerOff: FaPowerOff,
  phone: FaPhone,
  envelope: FaEnvelope,
  toggleOn: FaToggleOn,
  
  // Compatibilidad
  FaPenToSquare,
  FaTrash,
  FaDownload,
  FaPlus,
  FaUserPlus,
  FaPrint,
  FaCheck,
  FaThumbtack,
  FaFloppyDisk,
  FaCamera,
  FaKey,
  FaEraser,
  FaPowerOff,
  FaPhone,
  FaEnvelope,
  FaToggleOn,
  userCheck: FaUserCheck,
  FaUserCheck,
  calendarPlus: FaCalendarPlus,
  FaCalendarPlus,
  filterClear: FaEraser,

  paperPlane: FaPaperPlane,
  paperclip: FaPaperclip,
  trash: FaTrash,
  rotate: FaRotate,
  rotateLeft: FaRotateLeft,
  redo: FaRotateLeft,
  comment: FaComment,
  FaCommentAlt: FaComment,
  arrowsRotate: FaArrowsRotate,
  penToSquare: FaPenToSquare,
  xmark: FaXmark,
  times: FaXmark,
  FaPen: FaPenToSquare,
  FaTimes: FaXmark,
  FaXmark,
  FaPaperclip,

  floppyDisk: FaFloppyDisk,
};
