// src/components/ui/icon/core/categories/general.js
import {
  // Iconos que no encajan perfectamente en otras categorías
  FaBrain,
  FaCode,
  FaTerminal,
  FaFlask,
  FaGears,
  FaChartLine,
  FaChartBar,
  FaChartPie,
  FaDiagramProject,
  FaGaugeHigh,
  FaCodeBranch,
  FaMobile,
  FaDesktop,
  FaLaptop,
  FaTablet,
  FaWifi,
  FaCloud,
  FaDatabase,
  FaServer,
  FaShield,
  FaBolt,
  FaFire,
  FaWater,
  FaWind,
  FaMountain,
  FaTree,
  FaLeaf,
} from "react-icons/fa6";

export const generalIcons = {
  // Tecnología
  brain: FaBrain,
  code: FaCode,
  terminal: FaTerminal,
  flask: FaFlask,
  gears: FaGears,
  
  // Gráficas y análisis
  chartLine: FaChartLine,
  chartBar: FaChartBar,
  chartPie: FaChartPie,
  diagram: FaDiagramProject,
  diagramProject: FaDiagramProject,
  gauge: FaGaugeHigh,
  branch: FaCodeBranch,
  
  // Dispositivos
  mobile: FaMobile,
  desktop: FaDesktop,
  laptop: FaLaptop,
  tablet: FaTablet,
  
  // Conectividad
  wifi: FaWifi,
  cloud: FaCloud,
  database: FaDatabase,
  server: FaServer,
  shield: FaShield,
  
  // Utilidades
  bolt: FaBolt,
  fire: FaFire,
  water: FaWater,
  wind: FaWind,
  mountain: FaMountain,
  tree: FaTree,
  leaf: FaLeaf,
  
  // Compatibilidad con nombres Fa...
  FaBrain,
  FaCode,
  FaTerminal,
  FaFlask,
  FaGears,
  FaChartLine,
  FaChartBar,
  FaChartPie,
  FaDiagramProject,
  FaGaugeHigh,
  FaCodeBranch,
  FaMobile,
  FaDesktop,
  FaLaptop,
  FaTablet,
  FaWifi,
  FaCloud,
  FaDatabase,
  FaServer,
  FaShield,
  FaBolt,
  FaFire,
  FaWater,
  FaWind,
  FaMountain,
  FaTree,
  FaLeaf,
};