// src/components/ui/icon/categories/statusIcons.js
import {
  FaCircleCheck,
  FaCircleXmark,
  FaCircleInfo,
  FaCircleExclamation,
  FaCircleQuestion,
  FaTriangleExclamation,
  FaBan,
  FaSpinner,
  FaCirclePause,
  FaBell,
  FaBug,
  FaStar,
  FaLock,
  FaLockOpen,
  FaUserShield,
  FaUserSlash,
} from "react-icons/fa6";

export const statusIcons = {
  checkCircle: FaCircleCheck,
  FaCheckCircle: FaCircleCheck,
  xCircle: FaCircleXmark,
  FaTimesCircle: FaCircleXmark,
  info: FaCircleInfo,
  circleInfo: FaCircleInfo,
  exclamationCircle: FaCircleExclamation,
  question: FaCircleQuestion,
  warning: FaTriangleExclamation,
  exclamationTriangle: FaTriangleExclamation,
  triangleExclamation: FaTriangleExclamation,
  ban: FaBan,
  spinner: FaSpinner,
  pause: FaCirclePause,
  bell: FaBell,
  bug: FaBug,
  star: FaStar,
  lock: FaLock,
  lockOpen: FaLockOpen,
    pause: FaCirclePause, 
    userSlash: FaUserSlash,
  
  // Compatibilidad
  FaCircleCheck,
  FaCircleXmark,
  FaCircleInfo,
  FaCircleExclamation,
  FaCircleQuestion,
  FaTriangleExclamation,
  FaBan,
  FaSpinner,
  FaCirclePause,
  FaBell,
  FaBug,
  FaStar,
  FaLock,
  FaLockOpen,
  userShield: FaUserShield,
  shieldAlt: FaUserShield,
  FaUserShield,
  FaPauseCircle: FaCirclePause,
    FaUserSlash,
    FaInfoCircle:FaCircleCheck
};
